server:
  port: 8080

spring:
  datasource:
    username: root
    password: asuzncmi666
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

indexing-settings:
  sites:
    - url: "http://www.playback.ru"
      name: "Playback"
    - url: "https://volochek.life"
      name: "Volochek Life"
    - url: "http://radiomv.ru"
      name: "Radio MV"
    - url: "https://ipfran.ru"
      name: "IPFRAN"
    - url: "https://dimonvideo.ru"
      name: "DimonVideo"
    - url: "https://nikoartgallery.com"
      name: "Niko Art Gallery"
    - url: "https://et-cetera.ru/mobile/"
      name: "Et Cetera Mobile"
    - url: "https://www.svetlovka.ru"
      name: "Svetlovka"